xplorer1/config/routes.rb
Rails.application.routes.draw do



  devise_for :users
    resources :users
    resources :satellites do
    resources :comments
end
    get '/users/:id/about', to: 'users#about'
    get 'users/index'
    root "satellites#index"

   get '/satellites/:id', to: 'satellites#show'

  #
  get '/satellites/:id/comments/new', to: 'comments#new'
   post '/satellites/:id', to: 'comments#create'
  delete '/satellites/:id', to: 'comments#destroy'
end

xplorer1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

xplorer1/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :satellite
    belongs_to :user
    validates :title, presence: true, length: { minimum: 2}
    validates :content, presence: true

end

xplorer1/app/models/controller.rb
class Controller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

xplorer1/app/models/satellite.rb
class Satellite < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :name, presence: true, length: { minimum: 5}
  validates :description, presence: true
end

xplorer1/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOOMOpjdy88srHLrEfMmZB_HohTpLa_dyb4OLy0IQ7Ej6QEBQrE_ElDxA"
         validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

         has_many :comments

end

xplorer1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
    protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name,  :birthday, :email, :password, :birthday, :city, :state, :birthday, :remember_me)}
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :remember_me)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :birthday, :email, :password, :about, :current_password, :remember_me)}
  end

  def after_sign_in_path_for(resource_or_scope)
    if session[:user_return_to]== nil
      user_path(@user)
    else
      super
    end
  end

  private
  def after_sign_out_path_for(resource)
    new_user_session_path
  end

end

xplorer1/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_satellite
  before_action :find_comment, only: [:destroy, :comment_owner]
  before_action :comment_owner, only: [:destroy, :first_name]

  def index
    @comments = Comment.all.order('created_at DESC')
  end
  def new
    @comment = Comment.new
  end

  def create
      @satellite = Satellite.find(params[:satellite_id])
      @comment = @satellite.comments.create(params[:comment].permit(:title, :content))
      if current_user == nil
        flash[:error] = "You must be signed in"
        redirect_to new_user_session_path
        return
    else @comment.user_id = current_user.id
    end
      if @comment.save
        flash[:notice] = "Successfully created a comment"
      redirect_to satellite_path(@satellite)
    else
      flash[:error] = "Something went wrong"
      redirect_to satellite_path(@satellite.id)
      end
    end


  def destroy
  @comment.destroy
    redirect_to satellite_path(@satellite)
  end

  private
  def find_satellite
    @satellite = Satellite.find(params[:satellite_id])

  end

  def find_comment
    @comment = @satellite.comments.find(params[:id])
  end

  def comment_owner
    unless current_user.id == @comment.user_id
    end
  end
end

xplorer1/app/controllers/satellites_controller.rb
class SatellitesController < ApplicationController

  def  index
    @satellites = Satellite.all
    cookies[:lat_lon] = JSON.generate([47.68, -122.37])

  end

  def show
    sat_id = params[:id]
    @satellite = Satellite.find(sat_id)
  end

  def new
    @satellite = Satellite.new(satellite_params)
    if @satellite.save
      flash[:notice] = "Satellite was added"
      redirect_to satellite_path(@satellite)
    end
  end

  def create
    @satellite = Satellite.new(satellite_params)
    redirect_to ('/satellites')
  end

  def destroy
    @satellite = Satellite.find(params[:id])
    @satellite.destroy
  end


    private
    def post_params
      params.require(:satellite).permit(:name, :picture, :description)
    end
end

xplorer1/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_comments = @user.comments
  end

  def update
    @user = User.find(params[:id])
      if @user.update_attributes(secure_params)
        redirect_to user_path, :notice => 'no problems'
      else
        return
      redirect_to user_path, :notice => 'something went wrong'
      end
  end

  def about
    @user = User.find(params[:id])
  end

  private
    def secure_params
      params.require(:user).permit(:first_name, :last_name, :image, :about, :birthday, :city, :state)
    end
end

xplorer1/app/helpers/application_helper.rb
module ApplicationHelper
protected
  def full_name user
    user.first_name + " " + user.last_name
  end
end

xplorer1/app/helpers/carousel_helper.rb
module CarouselHelper
  def carousel_for(images)
    Carousel.new(self, images).html
  end

  class Carousel
    def initialize(view, images)
      @view, @images = view, images
      @uid = SecureRandom.hex(6)
    end

    def html
      content = safe_join([indicators, slides, controls])
      content_tag(:div, content, id: uid, class: 'carousel slide')
    end

    private

    attr_accessor :view, :images, :uid
    delegate :link_to, :content_tag, :image_tag, :safe_join, to: :view

    def indicators
      items = images.count.times.map { |index| indicator_tag(index) }
      content_tag(:ol, safe_join(items), class: 'carousel-indicators')
    end

    def indicator_tag(index)
      options = {
        class: (index.zero? ? 'active' : ''),
        data: {
          target: uid,
          slide_to: index
        }
      }

      content_tag(:li, '', options)
    end

    def slides
      items = images.map.with_index { |image, index| slide_tag(image, index.zero?) }
      content_tag(:div, safe_join(items), class: 'carousel-inner')
    end

    def slide_tag(image, is_active)
      options = {
        class: (is_active ? 'item active' : 'item'),
      }

      content_tag(:div, image_tag(image), options)
    end

    def controls
      safe_join([control_tag('left'), control_tag('right')])
    end

    def control_tag(direction)
      options = {
        class: "#{direction} carousel-control",
        data: { slide: direction == 'left' ? 'prev' : 'next' }
      }

      icon = content_tag(:i, '', class: "glyphicon glyphicon-chevron-#{direction}")
      control = link_to(icon, "##{uid}", options)
    end
  end
end

xplorer1/app/helpers/comments_helper.rb
module CommentsHelper
  
end

xplorer1/app/helpers/satellites_helper.rb
module SatellitesHelper
end

xplorer1/app/helpers/users_helper.rb
module UsersHelper

end

xplorer1/app/views/comments/_comment.html.erb
<div class="container bootstrap snippet">
  <div class="col-sm-2">
  </div>
  <div class="col-sm-8">
    <div class="panel panel-white post panel-shadow">
      <div class="post-heading">
        <div class="pull-left image">
          <img src="http://bootdey.com/img/Content/user_1.jpg" class="img-circle avatar" alt="user profile image">
        </div>
        <div class="pull-left meta">
          <div class="title h5">
              <% if current_user %>
              <b><%= full_name current_user %></b>
              <% end %>
            made a post.

          <h6 class="text-muted time">
            <p><%= time_ago_in_words(comment.created_at) %>
            ago</p></h6>
          </div>

        </div>
      </div>
      <%= comment.title %>
      <br>
      <br>
      <div class="post-description">
        <p><%= comment.content %></p>
        <br>
        <div class="stats">
          <% if current_user %>
          <%= link_to 'x Delete', [comment.satellite, comment], method: :delete, class: "btn btn-danger"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<br>

xplorer1/app/views/comments/_form.html.erb
<%= form_for [@satellite, @satellite.comments.build] do |f| %>
<% if user_signed_in? %>
<div class="container pb-cmnt-container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-info">
        <div class="panel-body">

          <h3>Write A Comment!</h3>
          <%= f.label :title %><br>
          <%= f.text_field :title, minimum: 5, type:'required' %><br>
          <%= f.label :comment %>

          <%= f.text_area :content, class:"pb-cmnt-textarea success" %>
<br>

            <%= f.submit 'Submit', class:'btn-primary btn-md', type:'submit'  %>

        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
<% end %>
<% end %>

xplorer1/app/views/comments/new.html.erb
<h1>Post A New Comment</h1>

<div class="container bootstrap snippet">


   <%= render 'form' %>
</div>

xplorer1/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

xplorer1/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav id="navbarstyle" class="navbar navbar-inverse navbar-fixed-top">
  <div class="container pull-left">
    <div class="navbar-header">

      <%= link_to 'Explorer1', root_path, class: 'navbar-brand' %>
      <% if !current_user %>
      <%= link_to "Sign up", new_user_registration_path, class: 'navbar-brand'  %>
      <% end %>
      <% if current_user %>
      <%= link_to "Profile", user_path(current_user.id), class: 'navbar-brand'  %>

      <% end %>
      <% if current_user %>
      <%= link_to 'Logout', destroy_user_session_path, class: 'navbar-brand',  :method => :delete %>
    <% else %>
      <%= link_to "Login",  new_user_session_path, class: 'navbar-brand'  %>
      <% end %>
    </div>
  </div>
  <div class="collapse navbar-collapse">

    <ul class="nav navbar-nav">

      <%= render 'layouts/navigation_links' %>

    </ul>

  </div>
</nav>

xplorer1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Xplorer1" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Xplorer1" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://fonts.googleapis.com/css?family=Share+Tech+Mono" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>

    <footer id="footer" class="footer-inverse text-center">

            © 2017 Copyright: <a href="https://github.com/LamarSmith92/x-plorer-1-app/tree/master/xplorer1"> Xplorer1 Dev Group </a>

  </body>
</html>

xplorer1/app/views/satellites/index.html.erb
<head>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAC_sT3NElJALYy-ynz7Xqs2aHm2kWfweM"></script>

</head>

<body>

  <div class="satellitelist">
    <h1 class="welcomeheading">
      Welcome to Explorer1
    </h1>
    <p class="welcomeintro">
      Where we track the International Space Station in real time.
    </p>

    <br />
<% @satellites.each do |satellite| %>
<p><%= satellite.description %></p>
  <% end %>
  </div>
  <div class='container'>
    <div class='row'>
    </div>
    <div id="map" class="gmaps4rails_map">
    </div>
      <% @satellites.each do |satellite| %>
    <div class="list-group pull-right">
  <%=link_to "I.S.S", "/satellites/#{satellite.id}", class:"list-group-item list-group-item-success" %>
  <%=link_to "LamAR7", "/satellites/#{satellite.id}", class:"list-group-item list-group-item-info" %>
  <%=link_to "CAR105", "/satellites/#{satellite.id}", class:"list-group-item list-group-item-warning" %>
  <%=link_to "S-4Y4", "/satellites/#{satellite.id}", class:"list-group-item list-group-item-danger" %>
  <% end %>
    </div>
  </div>
</div>

</body>

<script>
  var geocoder,
      map,
      markers = [],
      issImage = 'https://image.ibb.co/cxo9Qk/sat_x1_img.png',
      fakeSat1 = 'http://i.imgur.com/sc3lOok.png',
      fakeSat2 = 'http://i.imgur.com/VHhrXu5.png',
      fakeSat3 = 'http://i.imgur.com/sUXj0hE.png',
      issMarker ,
      fakeMarker1 ,
      fakeMarker2 ,
      fakeMarker3 ,
      fakeLat,
      fakeLng;
  function initMap() {
    geocoder = new google.maps.Geocoder()
    var mapOptions = {
      center: new google.maps.LatLng(37.79, -122.40),
      zoom: 6,
      mapTypeId: 'satellite'
    };
    map = new google.maps.Map(document.getElementById("map"), mapOptions);
  };
  $(document).on('ready', function () {
    // Actions to do
    setTimeout(function () {
      initMap();
      getTheData();
    }, 100);
    setInterval(getTheData, 1500);
  });
  //GEOCODER
  function codeAddress() {
    var address = document.getElementById('address').value;
    geocoder.geocode({
      'address': address
    }, function (results, status) {
      if (status == 'OK') {
        map.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({map: map, position: results[0].geometry.location});
      } else {
        console.log('Geocode was not successful for the following reason: ' + status);
      }
    });
  }
  function getTheData() {
    $.ajax({method: 'get', url: 'http://api.open-notify.org/iss-now.json', success: onSuccess, error: onError})
    function onSuccess(json) {
      //get the data we want and parseFloat
      var whatWeWant = json.iss_position;
      lat = parseFloat(whatWeWant.latitude);
      lng = parseFloat(whatWeWant.longitude);
      //set the marker to the way google map wants it
      var markerForMap = {
        lat: lat,
        lng: lng
      }
      // Define a symbol using SVG path notation, with an opacity of 1.
      var lineSymbol = {
        path: 'M 0,-1 0,1',
        strokeOpacity: 1,
        scale: 1
      };
      // Create the polyline. Give the line an opacity of 0. Repeat the symbol at intervals of 10 pixels.
      var line = new google.maps.Polyline({
        path: [
          {lat, lng},
          {lat,lng}
        ],
        strokeOpacity: 0,
        icons: [
          {
            icon: lineSymbol,
            offset: '0',
            repeat: '10px'
          }
        ],
        map: map
      });
      //add the fakeMarker here
      var fakeMarker = {
        lat: fakeLat,
        lng: fakeLng
      }
      generateFakeData(20);
      if (fakeMarker2){
        fakeMarker2.setPosition(fakeMarker)
      } else {
        fakeMarker2 = new google.maps.Marker({
          position: fakeMarker,
          map: map,
          title: 'this is a fake satellite',
          icon: fakeSat1,
          url: "/satellites/2"
        });
      }
      google.maps.event.addListener(fakeMarker2, 'click', function () {
        window.location.href = fakeMarker2.url
      });
      var fakeMarker = {
        lat: fakeLat,
        lng: fakeLng
      }
      generateFakeData(25);
      if (fakeMarker1) {
        fakeMarker1.setPosition(fakeMarker)
      } else {
        fakeMarker1 = new google.maps.Marker({
          position: fakeMarker,
          map: map,
          title: 'this is a fake satellite',
          icon: fakeSat2,
          url: "/satellites/3"
        });
      }
      google.maps.event.addListener(fakeMarker1, 'click', function () {
        window.location.href = fakeMarker1.url
      });
      var fakeMarker = {
        lat: fakeLat,
        lng: fakeLng
      }
      generateFakeData(-15);
      if (fakeMarker3) {
        fakeMarker3.setPosition(fakeMarker)
      } else {
        fakeMarker3 = new google.maps.Marker({
          position: fakeMarker,
          map: map,
          title: 'this is a fake satellite',
          icon: fakeSat3,
          url: "/satellites/2"
        });
      }
      google.maps.event.addListener(fakeMarker3, 'click', function () {
        window.location.href = fakeMarker3.url
      });
      //adding the iss marker in the map, the if statement only shows on maker
      if (issMarker) {
        issMarker.setPosition(markerForMap)
      } else {
        issMarker = new google.maps.Marker({
          // and pass in the poistion
          position: markerForMap,
          map: map,
          title: 'ISS',
          icon: issImage,
          url: "/satellites/1",
          id: "1"
        });
        map.setCenter(markerForMap);
      }
      google.maps.event.addListener(issMarker, 'click', function () {
        window.location.href = issMarker.url
      });
    }
    function onError(e1, e2, e3) {
      console.log("it didnt work e1", e1);
      console.log("it didnt work e2", e2);
      console.log("it didnt work e3", e3);
    }
  }
  function hideIssMarker() {
    issMarker.setMap(null);
  }
  function showIssMarker() {
    issMarker.setMap(map);
  }
  function generateFakeData(num) {
    //generate the latitude
    fakeLat = lat + num
    if (fakeLat > 90) {
      fakeLat -= 180
    } else if (fakeLat < -90) {
      fakeLat += 180
    }
    //generate the longitude
    fakeLng = lng + num
    if (fakeLng > 180) {
      fakeLng -= 360
    } else if (fakeLng < -180) {
      fakeLng += 360
    }
  }
</script>

xplorer1/app/views/satellites/show.html.erb
<div class="post-single">
  <%= link_to "Back", satellites_path %>
<div class="title">
<h2 class="satname text-center">  <%= @satellite.name %></h2>
</div>



<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
<!-- Indicators -->
<ol class="carousel-indicators">
  <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
  <li data-target="#carousel-example-generic" data-slide-to="1"></li>
  <li data-target="#carousel-example-generic" data-slide-to="2"></li>
</ol>

<!-- Wrapper for slides -->
<div class="carousel-inner">
  <div class="item active">
    <%= image_tag @satellite.picture %>
  </div>
  <div class="item">
    <%= image_tag 'http://i.imgur.com/wwtEIsf.jpg?1' %>
  </div>
  <div class="item">
    <%= image_tag 'http://i.imgur.com/ZwM2quz.jpg?1' %>
  </div>
  <div class="item">
    <%= image_tag 'http://i.imgur.com/la3UOok.jpg?1' %>
  </div>

  ...
</div>

<!-- Controls -->
<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
  <span class="glyphicon glyphicon-chevron-left"></span>
</a>
<a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
  <span class="glyphicon glyphicon-chevron-right"></span>
</a>
</div>

<div class="post-content">
<p><br><%= @satellite.description%></p>
</div>

<h4><%= @satellite.comments.count %> Comments </h4>
<%= render @satellite.comments %>
<%= render "comments/form" %>


</body>

xplorer1/app/views/users/about.html.erb
<%= form_for @user,  html: { multipart: true } do |f| %>
<div id="content">
  <%= full_name current_user %>

</div>
<% end %>

xplorer1/app/views/users/edit.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

xplorer1/app/views/users/show.html.erb
<%= form_for @user,  html: { multipart: true } do |f| %>

<div class="container">
  <div class="row profile">
    <div class="col-md-3">
      <div class="profile-sidebar">
        <!-- SIDEBAR USERPIC -->
        <div class="profile-userpic">
          <%= image_tag @user.image.url(:thumb) %>
        </div>

        <!-- END SIDEBAR USERPIC -->
        <!-- SIDEBAR USER TITLE -->
        <div class="profile-usertitle">
          <div class="profile-usertitle-name">
            <%= full_name current_user %>
          </div>

        </div>
        <!-- END SIDEBAR USER TITLE -->
        <!-- SIDEBAR BUTTONS -->
        <div class="profile-userbuttons">

          <div class='upload-img'>
            <label class="btn btn-default btn-file">
              <%= f.submit "upload" %>
            </label>

            <%= f.file_field :image, :class=>'btn pull-right' %>

          </div>

        </div>
        <!-- END SIDEBAR BUTTONS -->
        <!-- SIDEBAR MENU -->
        <div class="profile-usermenu">
          <ul class="nav">
            <li class="active">

            </li>

            <li>
              <a href="#" target="_blank">
                <i class="glyphicon glyphicon-ok"></i>
                Favorited Satellites</a>
            </li>
            <% if current_user %>
            <li>
              <a href="#">
                <i class="glyphicon glyphicon-user"></i>
                My Post
              </a>
            </li>
            <li>

         <%= link_to " Account Settings",  edit_user_registration_path, class: 'glyphicon glyphicon-flag' %>
            </li>
            <% end %>
          </ul>
        </div>
        <!-- END MENU -->
      </div>
    </div>
    <div class="col-md-9">
      <div class="profile-content">
          <h2>About Me</h2>
          <hr>
          <p>
        <%= @user.about %>
      </p>
      </div>
      <%= render @user.comments = @user.comments %>
    </div>
  </div>
</div>

<br>
<br>

<% end %>